### ISSUE TITLE
Undefined variable $pusher

### ISSUE THREAD

**Issue by mecha** [usebranch/branch-helper#2]
The plugin triggers two notices for an undefined `$pusher` variable. The notices originate from hook handlers that `use` a parent scope variable that does not exist.

Links:
* [branch-helper.php#L147](https://github.com/usebranch/branch-helper/blob/0.0.2/branch-helper.php#L147)
* [branch-helper.php#L168](https://github.com/usebranch/branch-helper/blob/0.0.2/branch-helper.php#L168)

It also seems like these `$pusher` variables are not being used and can be removed safely.

**Comment by petersuhm** [comment]
@mecha Thank you! Some WP Pusher leftover in there 😅 Just pushed a fix.
